openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts Manager
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing user's contacts
tags:
  - name: Contacts
    description: Operations related to user contacts
  - name: Auth
    description: Authentication and authorization operations
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-bo2j.onrender.com
paths:
  /contacts:  
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{id}/getById.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/reset-pwd.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    $ref: '../swagger/components/schemas.yaml'
  responses:
    $ref: '../swagger/components/responses.yaml'